# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Registration' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parse'

  # Pods for Registration

  target 'RegistrationTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Parse'
  end

  target 'RegistrationUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Parse'
  end

end
